import { useState, useCallback, useRef } from 'react';

// These types would be generated by wasm-bindgen
interface CADDocument {
  createBox(width: number, height: number, depth: number): string;
  createCylinder(radius: number, height: number): string;
  createSphere(radius: number): string;
  createCone(bottomRadius: number, topRadius: number, height: number): string;
  createTorus(majorRadius: number, minorRadius: number): string;
  booleanUnion(targetId: string, toolId: string): string;
  booleanSubtract(targetId: string, toolId: string): string;
  tessellate(featureId: string): MeshData;
  exportStl(featureId: string, binary: boolean): Uint8Array;
  exportObj(featureId: string): string;
  getFeatureIds(): string[];
  getFeatureInfo(featureId: string): FeatureInfo;
}

interface MeshData {
  positions: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
  vertexCount: number;
  triangleCount: number;
}

interface FeatureInfo {
  id: string;
  name: string;
  type: string;
  suppressed: boolean;
}

interface CADModule {
  CADDocument: new (name?: string) => CADDocument;
  version(): string;
}

let wasmModule: CADModule | null = null;
let wasmLoading = false;
let wasmError: string | null = null;

async function loadWasm(): Promise<CADModule> {
  if (wasmModule) return wasmModule;
  if (wasmLoading) {
    // Wait for existing load
    while (wasmLoading) {
      await new Promise((resolve) => setTimeout(resolve, 50));
    }
    if (wasmModule) return wasmModule;
    throw new Error(wasmError || 'WASM load failed');
  }

  wasmLoading = true;
  try {
    // Dynamic import of the WASM module
    const module = await import('../wasm/pkg/rcad_wasm.js');
    await module.default();
    wasmModule = module as unknown as CADModule;
    console.log('rCAD WASM loaded, version:', wasmModule.version());
    return wasmModule;
  } catch (e) {
    wasmError = e instanceof Error ? e.message : 'Unknown error';
    throw e;
  } finally {
    wasmLoading = false;
  }
}

export function useCAD() {
  const [isInitialized, setIsInitialized] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const documentRef = useRef<CADDocument | null>(null);

  const initialize = useCallback(async () => {
    try {
      const module = await loadWasm();
      documentRef.current = new module.CADDocument('Untitled');
      setIsInitialized(true);
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Failed to initialize CAD';
      setError(message);
      console.error('CAD initialization failed:', e);
    }
  }, []);

  const createBox = useCallback(
    async (width: number, height: number, depth: number) => {
      if (!documentRef.current) throw new Error('CAD not initialized');
      return documentRef.current.createBox(width, height, depth);
    },
    []
  );

  const createCylinder = useCallback(
    async (radius: number, height: number) => {
      if (!documentRef.current) throw new Error('CAD not initialized');
      return documentRef.current.createCylinder(radius, height);
    },
    []
  );

  const createSphere = useCallback(async (radius: number) => {
    if (!documentRef.current) throw new Error('CAD not initialized');
    return documentRef.current.createSphere(radius);
  }, []);

  const createCone = useCallback(
    async (bottomRadius: number, topRadius: number, height: number) => {
      if (!documentRef.current) throw new Error('CAD not initialized');
      return documentRef.current.createCone(bottomRadius, topRadius, height);
    },
    []
  );

  const booleanUnion = useCallback(
    async (targetId: string, toolId: string) => {
      if (!documentRef.current) throw new Error('CAD not initialized');
      return documentRef.current.booleanUnion(targetId, toolId);
    },
    []
  );

  const booleanSubtract = useCallback(
    async (targetId: string, toolId: string) => {
      if (!documentRef.current) throw new Error('CAD not initialized');
      return documentRef.current.booleanSubtract(targetId, toolId);
    },
    []
  );

  const tessellate = useCallback(async (featureId: string) => {
    if (!documentRef.current) throw new Error('CAD not initialized');
    return documentRef.current.tessellate(featureId);
  }, []);

  const exportStl = useCallback(
    async (featureId: string, binary = true) => {
      if (!documentRef.current) throw new Error('CAD not initialized');
      return documentRef.current.exportStl(featureId, binary);
    },
    []
  );

  const exportObj = useCallback(async (featureId: string) => {
    if (!documentRef.current) throw new Error('CAD not initialized');
    return documentRef.current.exportObj(featureId);
  }, []);

  return {
    initialize,
    isInitialized,
    error,
    cad: isInitialized
      ? {
          createBox,
          createCylinder,
          createSphere,
          createCone,
          booleanUnion,
          booleanSubtract,
          tessellate,
          exportStl,
          exportObj,
        }
      : null,
  };
}
